### ISSUE TITLE
Chrome Autofill

### ISSUE THREAD

**Issue by Targun** [ubilabs/react-geosuggest#176]
Chrome tries to autofill the address input, which lays on top of the autocomplete dropdown. Here is a stackoverflow I found about it:

http://stackoverflow.com/questions/15738259/disabling-chrome-autofill

<img width="354" alt="screen shot 2016-06-27 at 1 16 36 pm" src="https://cloud.githubusercontent.com/assets/6590633/16390641/688841d6-3c69-11e6-8c0b-b4019a1cd68e.png">

**Comment by Caerostris** [comment]
The post on stackoverflow explores only part of the issue and the solution. One author recommends setting autocomplete to `false` instead of `off`, suggesting that this solves the issue without further explanation.
This solution indeed happens to be the (almost) correct way to disable auto fill in Google Chrome.
The [MDN article](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) on the autocomplete tag suggests setting the autocomplete field to an invalid value in order to *really* disable auto complete and auto fill.
In March, Google [announced](https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164) that Chrome will deliberately ignore the `autocomplete=off` attribute, also suggesting to use invalid values to force disabling auto fill.
And, indeed, the [WHATWG specification](https://html.spec.whatwg.org/multipage/forms.html#autofill-processing-model) of the `autocomplete` attribute confirms that this is the case.

As a matter of fact, `false` is not a valid value, and therefore has the desired effect.
However, Google suggests to use semantically meaningful invalid values. Setting the field to something along the lines of `autocomplete=disable-autofill` should have the same effect as setting it to `false`, while also maintaining readability.

I'll attempt to reproduce the issue test these settings.

**Comment by Caerostris** [comment]
I am unable to reproduce this.
Which version of Geosuggest are you using?
Which version of Chrome are you using?

**Comment by Targun** [comment]
Thank you for looking into this!  

Chrome: Version 51.0.2704.103 (64-bit)
GeoSuggest: 1.18

I am going to upgrade GeoSuggest to see if it resolves.

**Comment by Caerostris** [comment]
Yup, please upgrade Geosuggest. We added a fix for a similar issue in the latest release, and it might also solve yours 👍

**Comment by Targun** [comment]
Upgrading seemed to fix it for me - Thanks @Caerostris!  Sorry for wasting your time.

**Comment by Caerostris** [comment]
No worries!

**Comment by HugoGiraudel** [comment]
Hello. The problem still exists with react-geosuggest 2.0.0 and Chrome 54 (possibly other versions). Any suggestion? :)
