### ISSUE TITLE
onSuggestSelect fires when there is no suggested selected

### ISSUE THREAD

**Issue by mkuipers** [ubilabs/react-geosuggest#191]
In using the `onSuggestSelect` event, I would expect it to fire only when a suggestion is selected.  If an input is entered and no suggestions are found based on the input and I press tab or enter, it fires the "onSuggestSelect" with the results of the geocoded user input value.  

This seems like unexpected behavior to me since no suggestion was selected, I would not expect `onSuggestSelect` to fire.  

## Example:

```
<Geosuggest
          onSuggestSelect={this.onSuggestSelect}
          types={['(cities)']}
          />

...

  onSuggestSelect: function(suggest) {
    console.log("onSuggestSelect selected this:", suggest); // eslint-disable-line
  }

```

![onsuggestselect problem](https://cloud.githubusercontent.com/assets/1087502/17304856/4ebf0cfe-57ed-11e6-8c07-7c72eece913f.gif)

In this example, I would not expect input "asdf" to fire an onSelect event for a location that was not selected.

**Comment by ro-ka** [comment]
We do a geocoding of the entered string because some users may not want to select but instead just type *nyc* and hit enter. In that case there should be a geocoding of that entered string. For the unexpected result you got: There is a place called *asdf* in New York. See [Google Maps](https://www.google.de/maps/place/asdf,+New+York,+NY+10021,+USA/@40.771254,-73.9696496,17z/data=!4m13!1m7!3m6!1s0x89c258ece8f64399:0x7b6122ee087effcb!2sasdf,+New+York,+NY+10021,+USA!3b1!8m2!3d40.77125!4d-73.9674556!3m4!1s0x89c258ece8f64399:0x7b6122ee087effcb!8m2!3d40.77125!4d-73.9674556).

It’s an unexpected result, yes. But it’s not unexpected behaviour.

**Comment by mkuipers** [comment]
I do not think it is unexpected behavior to geocode the input. That seems totally reasonable.  However, I maintain it is absolutely unexpected behavior to fire the onSuggestSelect when no suggest is selected.
