### ISSUE TITLE
Removing United States from results

### ISSUE THREAD

**Issue by Targun** [ubilabs/react-geosuggest#24]
I'd like to remove Untied States from results.  I did this which worked.  Is there a more elegant way?

```javascript
if(suggest.label.substr(suggest.label.length - 13) === "United States") {
    suggest.label = suggest.label.substring(0, suggest.label.length - 15);
}
```

In the getSuggestItems function on line 268

**Comment by ro-ka** [comment]
Hey, since release `1.6.0` yesterday you can limit the suggestions to specific countries. See the [Readme](https://github.com/ubilabs/react-geosuggest#country) on how to use.

It is not possible, though, to exclude specific countries in the Google Autocomplete Service. And I don’t see much value in prohibiting specific countries… What is your use case? Can you get better suggest results by using a `country` or by using `bounds`?

**Comment by Targun** [comment]
The value is fit the addresses nicely into a small input.  We can close this issue.

**Comment by ro-ka** [comment]
Perfect!
