### ISSUE TITLE
Fallback when certain placeIds returned by autocomplete don't match anything in geocoder

### ISSUE THREAD

**Issue by brmenchl** [ubilabs/react-geosuggest#258]
###### Example
Typing in 2005 N Amelia St autocompletes to 2005 N Amelia St, Sterling, VA, United States. The `placeId` returned by google is sent to the geocoder when selected, and the google geocoder returns `ZERO_RESULTS`.

It looks like some `placeId`s returned by the autocomplete service aren't recognized by other Google services (You can check the same example in [Google's autocomplete example](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform)). Within `geocodeSuggest`, the `placeId` is used if it exists, however, that id could be unrecognized.

I propose having a fallback. If `placeId` is used to call the geocoder and the response is `ZERO_RESULTS`, the geocoder is called again with the suggest label/address string. This _does_ work in the case above. If the fallback also fails we proceed as before.
This will of course give us two calls where before we had one, but only in the case of a geocoder empty response. With this solution, we get the speed of using a placeId in most cases, and we get a successful response in edge cases.

**Comment by rodcope1** [comment]
I have the same issue with a simple address: 13890 Gunnison Way, Broomfield, CO.  Autocomplete works well, but the placeId returned gives ZERO_RESULTS when asking the geocoder for details.

The current code uses getPlacePredictions, which apparently returns bad placeId's in some cases.  When I tested the same address above in an autocomplete field from a Google code sample, it returned a different placeId that could be used to return good results.  

Consider switching to using Google's autocomplete field directly instead of manually grabbing the predictions and looking up the chosen one later?

**Comment by rajington** [comment]
It seems Google has been trying to phase out the shorter place IDs in exchange for longer ones. A lot of people are upset about the issues this has caused: https://code.google.com/p/gmaps-api-issues/issues/detail?id=11107

Now that the autocomplete service has been upgraded to use longer place IDs, they're recommending (forcing) using a different service altogether instead of `Geocoder`. The code will have to be updated to use [Place Details](https://developers.google.com/maps/documentation/javascript/places#place_details) instead. The fix is simple enough and the response is almost the same, but this will also require devs to enable this new API in the console, so it's really a breaking change.

**Comment by rajington** [comment]
I can submit a PR but not sure how you want to handle the breaking change. A quick comparison of the differences in the response (fill in your own API key):

**Geocode API**
Reference: https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingResponses
Example:
https://maps.googleapis.com/maps/api/geocode/json?place_id=ChIJOyk4mdw5tokRzAoSf-Az58Q&key=
```
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "2005",
               "short_name" : "2005",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "North Amelia Street",
               "short_name" : "N Amelia St",
               "types" : [ "route" ]
            },
            {
               "long_name" : "Sterling",
               "short_name" : "Sterling",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Loudoun County",
               "short_name" : "Loudoun County",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "Virginia",
               "short_name" : "VA",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "United States",
               "short_name" : "US",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "20164",
               "short_name" : "20164",
               "types" : [ "postal_code" ]
            },
            {
               "long_name" : "3511",
               "short_name" : "3511",
               "types" : [ "postal_code_suffix" ]
            }
         ],
         "formatted_address" : "2005 N Amelia St, Sterling, VA 20164, USA",
         "geometry" : {
            "bounds" : {
               "northeast" : {
                  "lat" : 39.0228319,
                  "lng" : -77.3880442
               },
               "southwest" : {
                  "lat" : 39.0226199,
                  "lng" : -77.3882831
               }
            },
            "location" : {
               "lat" : 39.0227259,
               "lng" : -77.38816369999999
            },
            "location_type" : "ROOFTOP",
            "viewport" : {
               "northeast" : {
                  "lat" : 39.02407488029149,
                  "lng" : -77.38681466970849
               },
               "southwest" : {
                  "lat" : 39.02137691970849,
                  "lng" : -77.38951263029151
               }
            }
         },
         "place_id" : "ChIJOyk4mdw5tokRzAoSf-Az58Q",
         "types" : [ "premise" ]
      }
   ],
   "status" : "OK"
}
```

**Place Details**
Reference: https://developers.google.com/maps/documentation/javascript/places#place_details_responses
Example:
https://maps.googleapis.com/maps/api/place/details/json?placeid=ChIJX7c5mdw5tokRzNZodJ4Ql1eaBi0yMDA1IE4gQW1lbGlhIFN0LCBTdGVybGluZywgVkEsIFVuaXRlZCBTdGF0ZXM&key=
```
{
   "html_attributions" : [],
   "result" : {
      "address_components" : [
         {
            "long_name" : "2005",
            "short_name" : "2005",
            "types" : [ "street_number" ]
         },
         {
            "long_name" : "North Amelia Street",
            "short_name" : "N Amelia St",
            "types" : [ "route" ]
         },
         {
            "long_name" : "Sterling",
            "short_name" : "Sterling",
            "types" : [ "locality", "political" ]
         },
         {
            "long_name" : "Sterling",
            "short_name" : "Sterling",
            "types" : [ "administrative_area_level_3", "political" ]
         },
         {
            "long_name" : "Loudoun County",
            "short_name" : "Loudoun County",
            "types" : [ "administrative_area_level_2", "political" ]
         },
         {
            "long_name" : "Virginia",
            "short_name" : "VA",
            "types" : [ "administrative_area_level_1", "political" ]
         },
         {
            "long_name" : "United States",
            "short_name" : "US",
            "types" : [ "country", "political" ]
         },
         {
            "long_name" : "20164",
            "short_name" : "20164",
            "types" : [ "postal_code" ]
         },
         {
            "long_name" : "3511",
            "short_name" : "3511",
            "types" : [ "postal_code_suffix" ]
         }
      ],
      "adr_address" : "\u003cspan class=\"street-address\"\u003e2005 N Amelia St\u003c/span\u003e, \u003cspan class=\"locality\"\u003eSterling\u003c/span\u003e, \u003cspan class=\"region\"\u003eVA\u003c/span\u003e \u003cspan class=\"postal-code\"\u003e20164-3511\u003c/span\u003e, \u003cspan class=\"country-name\"\u003eUSA\u003c/span\u003e",
      "formatted_address" : "2005 N Amelia St, Sterling, VA 20164, USA",
      "geometry" : {
         "location" : {
            "lat" : 39.0227259,
            "lng" : -77.38816369999999
         },
         "viewport" : {
            "northeast" : {
               "lat" : 39.02279974999999,
               "lng" : -77.38781315000001
            },
            "southwest" : {
               "lat" : 39.02250435000001,
               "lng" : -77.38828054999999
            }
         }
      },
      "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
      "id" : "79ef3114579370bcf9c6bfdbef89987e3ce5c800",
      "name" : "2005 N Amelia St",
      "place_id" : "ChIJOyk4mdw5tokRzAoSf-Az58Q",
      "reference" : "CmRbAAAAVHSDMDuuIEGHxwwntIFUJEsRJG2eZALs2xn_yXRLtetJghZ6ze5IP4cUT9DpsJRyeJ4HhmUVBG_6qHJFuuG7tqky9jnHZwNGrKLvmu_4Iz39Z019CktBa0YViRPsTyL1EhATv338tJwMdr_3yTOMkrLpGhR-LePLkNVCg1eP-zFsied0HK4atg",
      "scope" : "GOOGLE",
      "types" : [ "premise" ],
      "url" : "https://maps.google.com/?q=2005+N+Amelia+St,+Sterling,+VA+20164,+USA&ftid=0x89b639dc9938293b:0xc4e733e07f120acc",
      "utc_offset" : -300,
      "vicinity" : "Sterling"
   },
   "status" : "OK"
}
```

**Comment by ro-ka** [comment]
I guess the reason there aren’t results anymore is because Google changed the behavior of their geocoders. The Places geocoder is returning places results only now and the Address Geocoder is returning address results only now. See https://maps-apis.googleblog.com/2016/11/address-geocoding-in-google-maps-apis.html

**Comment by ro-ka** [comment]
We’ll need some way to specify whether the places or address geocoder should be used.

**Comment by ro-ka** [comment]
There is already a PR #240 by @ash-developer. Could this be the solution?

**Comment by rajington** [comment]
It's one solution but not the ideal one.

First, it attempts to Geocode a partial address which can return multiple responses, but it's not the same intelligent suggestions you get from the Places Autocomplete.

Current:
![master](https://cloud.githubusercontent.com/assets/53535/21625423/987a719c-d1d9-11e6-99b3-315c39e899d1.gif)

Using the PR #240:
![pr](https://cloud.githubusercontent.com/assets/53535/21625426/9b337302-d1d9-11e6-955f-a530b0e5eeb6.gif)

Second (and not a huge issue, but rather a suggestion for improvement if that's the route you take) it Geocodes the selected geocoded result again rather than using the data already retrieved.

We plan on dropping the Geocoding service completely, and using only the Place Autocomplete and Place Details services together, which I think is Google's preferred approach according to their examples and your attached blog post.

**Comment by rajington** [comment]
It seems sometime recently Google went ahead and made the Place Autocomplete service and Geocoder service compatible, all the new `place_id`s work. From what I can see, all the discussions about the **New Geocoder** on the blog post and FAQ only mention _forward geocoding_ and the deadlines they list shouldn't affect anything with `place_id`s but I've asked the question on the [original issue](https://code.google.com/p/gmaps-api-issues/issues/detail?id=11107#c49). My guess is that something was just temporarily messed up.

My fork using the `Place Details` was kind of annoying because the Place Details service **REQUIRES** that you pass in a DOM element. I added it as a prop, with a hidden div default, not too complicated but I'm going to create a PR and then immediately close it in case this ever comes up again. Thanks.

**Comment by ro-ka** [comment]
Thanks for checking this! So this issue isn’t needed anymore, right?

**Comment by rajington** [comment]
yeah, it'll still be trackable in case it needs to be re-opened but everything _should_ continue to work at this poitn
