### ISSUE TITLE
Make it work with react 0.14.0-beta3

### ISSUE THREAD

**Issue by boosh** [ubilabs/react-geosuggest#27]
Great library. I'd love to use it, but I'm a react noob. I can't get this to work with my project based on relay-starter-kit, which uses react 0.14.0-beta3. For some reason, I can't get anything useful to install when I fork and upgrade the dependency. When I install via npm (there's no actual source, just the meta files like package.json).

A fix (maybe an alternative branch) would be very helpful.

Thanks!

**Comment by ro-ka** [comment]
When you install with npm, there should be a `module` folder which contains the code. Not the ES6 source code, but the ES5 compiled code.

I’m not sure why it shouldn’t work with React 0.14. Is there any error thrown?

There is no official changelog yet, so I won’t make changes now. But there will be an update when React 0.14 is released officially.

If you find out what causes the problems, let me know!

**Comment by TylerBrock** [comment]
bump

**Comment by ro-ka** [comment]
Did someone fine out what’s wrong? The `module` folder should be in an npm install and be loaded.

**Comment by leoasis** [comment]
I think the problem the user is having is when installing via npm with the path pointing to the forked repo url. Since the `modules` dir is not in git (is created in a task before publishing the package) it does not appear in `node_modules` after `npm install`. Also the rest of the files in `.npmignore` are, well, ignored as well so it only contains the package.json and some other files.

So, to sum up, it _should_ work as is with React 0.14 (after a version bump in the peer dependencies, @ro-ka), and @boosh in your fork you need to add the `modules` folder as part of your git repo and push the built bundle.

**Comment by ro-ka** [comment]
So the peer dependency got bumped to `0.14.0`. For me it is working… Can you confirm?

**Comment by ro-ka** [comment]
Suspect that it is working. Reopen, if not.

**Comment by leoasis** [comment]
@ro-ka sorry for not reaching back, didn't actually use the released version until yesterday. Working fine for me! :D

**Comment by ro-ka** [comment]
Great to hear!
