### ISSUE TITLE
formatMatchedText breaking ligatures

### ISSUE THREAD

**Issue by salzhrani** [ubilabs/react-geosuggest#335]
### Short description

`formatMatchedText` is braking Arabic text (possibly other scripts that rely on ligatures 

### Expected results

if you search for 'جدة' you should get 'جدة ، مكة المكرمة'

### Actual results

ligatures are broken, text looks funny

I would suggest adding a prop to opt-out of the formatting

**Comment by ro-ka** [comment]
This is not desired, thanks for bringing it up!

The problem is indeed in that function as it adds the characters as individuals to the DOM. My preferred solution would be to concat the unmatched input before adding to the DOM so the ligatures work again. Adding another prop doesn’t solve the problem but would be a workaround.
