### ISSUE TITLE
What is the best way to extract the country from the result?

### ISSUE THREAD

**Issue by booboothefool** [ubilabs/react-geosuggest#344]
![screen shot 2017-08-19 at 12 27 37 pm](https://user-images.githubusercontent.com/13257645/29488465-d882a2ec-84d9-11e7-8e87-186ebbda954e.png)

So it seems like there a few fields which mention the country, but which is reliable to use for every result?

**Comment by cyrilf** [comment]
I think you can have more information from the [Google Places API directly](https://developers.google.com/places/web-service/details#PlaceDetailsResponses)

Otherwise, you can read this [Stack Overflow answer](https://stackoverflow.com/a/35199754/1410020) where you can see that:
> you can't guarantee what fields it will contain

So basically, you can `map` over `result.gmaps.address_components` and search in the `types` key if there is a `"country"` string. If so, you're good. If not, then you have to ask your user for it.

**Comment by ro-ka** [comment]
The result is what is returned from Google unchanged. As @cyrilf mentioned, mapping over the results is the way to go.

@cyrilf Thanks for answering!
