### ISSUE TITLE
country as an array can throw error

### ISSUE THREAD

**Issue by joannamilster** [ubilabs/react-geosuggest#356]
### Short description

I was trying to use this library's feature that allows `country` to be an array. Example: `[us, ca]`

### Expected results

The autosuggest populates with the correct cities from the correct countries when I start typing, when I hit enter (as opposed to clicking one explicitly), it should return a result with the best guess.

### Actual results

I get an error. `componentRestrictions: in property country: not a string`

It works if I only have one country (string) `country={'us'}` but this will make it blow up: `country={['us', 'ca']}`.

Maybe it has something to do with this line: https://github.com/ubilabs/react-geosuggest/blob/ec4c0abd108b3729294907fe8d12074cc62d27e2/src/Geosuggest.jsx#L198 or this line: https://github.com/ubilabs/react-geosuggest/blob/ec4c0abd108b3729294907fe8d12074cc62d27e2/src/Geosuggest.jsx#L386 ?

**Comment by ro-ka** [comment]
It works as expected here… Can you provide more information?

**Comment by joannamilster** [comment]
export default class SearchBars extends React.Component<any> {

    onSuggestSelect = (suggest: any) => {
        console.log('suggest', suggest)
    }
    render() {   
        return (
            <div className={`s2p-search-bars`}>
                        <Geosuggest
                            placeholder="City or Zip"
                            types={['(regions)']}
                            country={['us', 'ca']}
                            onSuggestSelect={this.onSuggestSelect}
                        />
            </div>
        )
    }

}

**If I type 'ddd' and then hit enter**, I get console error InvalidValueError: in property componentRestrictions: in property country: not a string

If I replace ` country={['us', 'ca']}` with ` country={'us'}` and type 'ddd' and hit enter I get a location back

**Comment by ro-ka** [comment]
Thanks for the clarification! Got the error now, too.

The problem seems to be that the geocoder has a different specification for the componentRestrictions (the country): https://developers.google.com/maps/documentation/javascript/reference?csw=1#GeocoderComponentRestrictions

In the Place Predictions request a string and an array is allowed: https://developers.google.com/maps/documentation/javascript/reference?csw=1#ComponentRestrictions

So how to solve this? These are some options:

1. Just use the first country in the passed list for the geocoding.
2. Remove componentRestriction from geocoding.
3. Make a breaking change and only allow one country as a string, not an array.
4. Make multiple geocodings — but which result to use then?

I would opt for the first option as it still allows multiple countries to limit the requests to.

**Comment by ro-ka** [comment]
Tested right now, works now with the Maps API!

**Comment by Cryt1c** [comment]
I just stumbled upon this thread because I am having the same issue. We have set fixtures and a country limitation (["de", "cz", "pl", "dk", "nl"]) in the configuration.
When I select a fixture I get the error. If I use another value than a fixture it's working.
https://user-images.githubusercontent.com/8447640/130211869-e1823dff-3406-4ba5-8f42-3314430e06d4.mp4

Do you know a way to fix this or work around this issue?
