### ISSUE TITLE
Sorting / operating on suggestions before list render

### ISSUE THREAD

**Issue by ericorruption** [ubilabs/react-geosuggest#358]
Is this something you would be willing to have on the API?

My use case is sorting the suggestions to give emphasis to `transit_station` type suggestions, so that they would appear on top.

I think #348 allows this to happen.

**Comment by ro-ka** [comment]
I don’t think this should be in the scope of the component — doing this externally via #348 could be a solution.

The results returned by Google are limited and the fixtures get mixed in there, too. So I think it would irritate to resort them as it could appear that all the transit results are in the list already but in reality they are not yet in the list due to the limitations.

**Comment by ro-ka** [comment]
#348 is merged, so I’m closing this.
