### ISSUE TITLE
Using geosuggest.update(value) within onSuggestSelect causes an input flicker.

### ISSUE THREAD

**Issue by dilizarov** [ubilabs/react-geosuggest#378]
### Short description
`<Geosuggest onSuggestSelect={onSuggestSelect} ref={input => this.geosuggest = input} />`

If I type in a partial search ("Oak"), I see a list of autocompletes. The one I want is "Oakland, USA, ..." I select the autocomplete option I want, and `props.onSuggestSelect` gets triggered. In my onSuggestSelect function, I have logic that boils down to `this.geosuggest.update('some string')`.

Ultimately, it works and the input now reads 'some string', but there is a very quick flicker where 'Oak' gets changed to the label of the selected suggest ("Oakland, USA, ..." in this case), and then switches to 'some string'.

### Expected results

The expected results are that the input would read 'some string' when I clicked the suggest.
The above description should be enough to replicate. I basically know why this was happening and am wondering if there is a quick way around it short of forking the library and fixing it myself.

**Comment by dilizarov** [comment]
I ended up forking the Repo and making the changes I needed.

**Comment by yfr** [comment]
Hey. Sounds quite interesting. We never saw this flicker. Do you mind open a PR?

**Comment by mgmarlow** [comment]
I am running into this same issue since I don't see any other way to have a different value for the input's display and the actual selection. For example, I want to select "1234 Street, 12345, California" but want "1234 street, CA" to show up in the input.

The flickering occurs because `update` is called twice, once by default in the library implementation, once again from the `props.onSuggestSelect` call.

**Comment by ro-ka** [comment]
Please provide a demo or a PR to this.

**Comment by ro-ka** [comment]
Closing this because there is no feedback. Reopen if this problem still exists and provide an example.
