### ISSUE TITLE
calling clear() onFocus ?

### ISSUE THREAD

**Issue by andyfenelon** [ubilabs/react-geosuggest#75]
Im sure this is straight forward but im getting
Uncaught TypeError: Cannot read property 'clear' of undefined

to make the input clear onFocus

using refs as described
https://facebook.github.io/react/docs/more-about-refs.html
```
  onFocus() {
    this.geosuggest.clear();
  }


<Geosuggest
   ref={(ref) => this.geosuggest = ref}
  onFocus={this.onFocus}
/>
```
Thanks in advance.

**Comment by ro-ka** [comment]
Hm, that’s strange. Will need to check that…

**Comment by ro-ka** [comment]
I just checked the exact same code you provided and it worked… Used the example and added your two lines of code.

**Comment by BesatZardosht** [comment]
I get exact error!

**Comment by ro-ka** [comment]
Is the reference set up correctly? Does `this.geosuggest` or `this.refs` (depending on how the ref is set up) return the rendered element?

**Comment by BesatZardosht** [comment]
Thanks! The problem was that I was using this.refs.geosuggest instead of this.geosuggest!!
However, I am not sure why I cannot use ref="geosuggest" on my component I get this error:

`ddComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded
`

**Comment by ro-ka** [comment]
See response in #54 – it’s the same question.

**Comment by BesatZardosht** [comment]
I solved the problem. The problem was I was trying to reference it in the render function.
Thanks for the help! and great component
